import { StyleSheet } from 'react-native';
import colors from '../../assets/themes/colors';

export default StyleSheet.create({
    videoPlayer: {
        width: '100%',
        height: 300,
        backgroundColor: colors.black,
    },
    addButton: {
        borderRadius: 10,
        height: 30,
        width: 120,
        backgroundColor: colors.secondary,
        textAlign: 'center',
        textAlignVertical: 'center',
        color: colors.black,
        fontWeight: 'bold',
        alignSelf: 'center',
    },
    titleAndButton: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
    },
    subtitle: {
        fontWeight: 'bold',
        color: colors.black,
        fontSize: 20,
        paddingLeft: 10,
    },
    buttonIcon: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 10,
        backgroundColor: colors.lightgrey,
        borderRadius: 15,
        margin: 5,
    },
    buttonContainer: {
        flexDirection: 'row',
        alignContent: 'center',
        alignItems: 'center',
        // justifyContent: 'center',
    },
    editMode: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
    },
    editButton: {
        borderRadius: 50,
        height: 50,
        width: 'auto',
        backgroundColor: colors.primary,
        textAlign: 'center',
        textAlignVertical: 'center',
        alignSelf: 'center',
        marginHorizontal: 20,
    },
    functionButton: {
        borderRadius: 50,
        height: 50,
        backgroundColor: colors.secondary,
        textAlign: 'center',
        textAlignVertical: 'center',
        color: colors.black,
        fontWeight: 'bold',
        alignSelf: 'center',
        marginHorizontal: 40,
    },
    functionText: {
        fontWeight: 'bold',
        color: colors.black,
        fontSize: 20,
        padding: 10,
    },
    progressBar: {
        width: "95%",
        height: 50,
        flexDirection: 'row',
        alignSelf: 'center',
    },
    editText: {
        fontWeight: 'bold',
        textAlign: 'center',
        textAlignVertical: 'center',
        color: colors.black,
        fontSize: 15,
        padding: 13,
    },
});
