name: Android CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: "11"
                  distribution: "temurin"
                  cache: gradle

            - name: npm install
              working-directory: ./frontend
              run: npm install

            - name: Init gradlew wrapper
              working-directory: ./frontend/android
              run: ./gradlew wrapper --gradle-version=7.5.1

            - name: Grant execute permission for gradlew
              working-directory: ./frontend/android
              run: chmod +x ./gradlew
            - name: Build with Gradle
              working-directory: ./frontend/android
              run: ./gradlew build

            - name: React Native CI
              # You may pin to the exact commit or the version.
              # uses: aslamanver/react-native-docker@09bda07b4ca86691ab0e39e6ad197389e55a37a1
              uses: aslamanver/react-native-docker@v1
